import type { Metadata } from 'next';
import './globals.css';
import Footer from './components/common/Footer';

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="i4wbm5-">
            <body className="" data-oid="44wcwov">
                {children}
                <Footer />
            </body>
        </html>
    );
}
