 codex/search-for--root@--occurrences-and-clean-files


apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentix-backend
  namespace: zentix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentix-backend
  template:
    metadata:
      labels:
        app: zentix-backend
    spec:
      containers:
        - name: backend
          image: zentix/backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: zentix-backend
  namespace: zentix
spec:
  selector:
    app: zentix-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentix-frontend
  namespace: zentix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentix-frontend
  template:
    metadata:
      labels:
        app: zentix-frontend
    spec:
      containers:
        - name: frontend
          image: zentix/frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zentix-frontend
  namespace: zentix
spec:
  selector:
    app: zentix-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
 main
